package cn.luo.sortout.model.entity;

import org.greenrobot.greendao.annotation.*;

import java.util.List;
import cn.luo.sortout.model.dao.DaoSession;
import org.greenrobot.greendao.DaoException;

import cn.luo.sortout.model.dao.FolderDao;
import cn.luo.sortout.model.dao.PlanDao;
import cn.luo.sortout.model.dao.SuffixDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "folder".
 */
@Entity(active = true, nameInDb = "folder")
public class Folder {

    @Id
    @Property(nameInDb = "id")
    private Long id;

    @Property(nameInDb = "path")
    @NotNull
    @Unique
    private String path;

    /** Used to resolve relations */
    @Generated
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated
    private transient FolderDao myDao;

    @ToMany
    @JoinEntity(entity = PlanAndFolder.class, sourceProperty = "folderId", targetProperty = "planId")
    private List<Plan> planList;

    @ToMany
    @JoinEntity(entity = FolderAndSuffix.class, sourceProperty = "folderId", targetProperty = "suffixId")
    private List<Suffix> suffixList;

    @Generated
    public Folder() {
    }

    public Folder(Long id) {
        this.id = id;
    }

    @Generated
    public Folder(Long id, String path) {
        this.id = id;
        this.path = path;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getFolderDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(@NotNull String path) {
        this.path = path;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Plan> getPlanList() {
        if (planList == null) {
            __throwIfDetached();
            PlanDao targetDao = daoSession.getPlanDao();
            List<Plan> planListNew = targetDao._queryFolder_PlanList(id);
            synchronized (this) {
                if(planList == null) {
                    planList = planListNew;
                }
            }
        }
        return planList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetPlanList() {
        planList = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    @Generated
    public List<Suffix> getSuffixList() {
        if (suffixList == null) {
            __throwIfDetached();
            SuffixDao targetDao = daoSession.getSuffixDao();
            List<Suffix> suffixListNew = targetDao._queryFolder_SuffixList(id);
            synchronized (this) {
                if(suffixList == null) {
                    suffixList = suffixListNew;
                }
            }
        }
        return suffixList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    @Generated
    public synchronized void resetSuffixList() {
        suffixList = null;
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void delete() {
        __throwIfDetached();
        myDao.delete(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void update() {
        __throwIfDetached();
        myDao.update(this);
    }

    /**
    * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
    * Entity must attached to an entity context.
    */
    @Generated
    public void refresh() {
        __throwIfDetached();
        myDao.refresh(this);
    }

    @Generated
    private void __throwIfDetached() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
    }

}
